### ISSUE TITLE
compare clean data and standard data

### ISSUE THREAD

**Issue by alvizek** [SRJPE/jpe-battle-adult-edi#3]
One more double check to confirm that the standard data doesn't exclude any important variables that are in the raw dataset.

**Comment by liz-fw** [comment]
there are a few columns in the `battle_redd.csv` that we can confirm with the stream team:
- `pre_redd_depth`
- `redd_pit_depth`
- `redd_tail_depth`
- `start_flow_meter`, `start_flow_meter_80` (little data)
- `end_flow_meter`, `end_flow_meter_80` (little data)
- `flow_meter_time`, `flow_meter_time_80` (little data)
- `redd_loc` (river left, river center, river right)

I think we likely don't need these unless the stream team feels that people might be interested in the redd data to use the flow bomb/redd depth information in a study
